package dk.magenta.dafosts.clientcertificates;

import dk.magenta.dafosts.library.DatabaseQueryManager;
import dk.magenta.dafosts.library.SharedConfig;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.jdbc.core.JdbcTemplate;

@SpringBootApplication
@ComponentScan(basePackages = {"dk.magenta.dafosts.clientcertificates", "dk.magenta.dafosts.library"})
public class DafoStsByCertificateApplication {

    /**
     * A bean for the querymanager
     * @param jdbcTemplate - the jdbcTemplate generated by Spring Boot.
     * @return The DatabaseQueryManager
     */
	@Bean
    DatabaseQueryManager databaseQueryManager(JdbcTemplate jdbcTemplate) {
        DatabaseQueryManager manager = new DatabaseQueryManager(jdbcTemplate);
        manager.getLocalIdpUsers();
        return manager;
    }

	/**
	 * Load shared config from dafo-sts-library
	 * @return SharedConfig bean
	 */
	@Bean
	SharedConfig sharedConfigBean() {
		return new SharedConfig();
	}


	public static void main(String[] args) throws Exception {
		// Boostrap the Opensaml Library to use default configuration
		org.opensaml.DefaultBootstrap.bootstrap();

		// Run the application
		SpringApplication.run(DafoStsByCertificateApplication.class, args);
	}
}
