version: '3.5'
services:


  # df
  #---------
  datafordeler-gl:
    build:
      context: .
      dockerfile: ci/dockerFile
    environment:
      SERVER_PORT: 8080
    ports:
      - 8080:8083

volumes:
  datafordeler-gl:
