version: '3.5'
services:
  datafordeler:
    build:
      context: .
      dockerfile: docker/dockerFile
    depends_on:
      - datafordeler-db
    volumes:
      - ./docker/dev-env/application:/app/dev-env/local
    ports:
      - 8081:80
      - 5005:5005
    command: java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -jar datafordeler-core-exec.jar

  test:
    build:
      context: .
      dockerfile: docker/dockerFile
    depends_on:
      - datafordeler-db
    ports:
      - 8082:80
    command: bash -c "cd /code && mvn --batch-mode -T 2C test"
    #use docker-compose test to execute tests

  datafordeler-db:
    build:
      context: .
      dockerfile: docker/dockerFile.sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=testTEST1
    volumes:
      - ./docker/dev-env/local:/app/dev-env/local
      - ./docker/dev-env/db/initiate-db.sql:/app/initiate-db.sql
      - ./docker/manual_initiate.sh:/app/manual_initiate.sh

volumes:
  datafordeler-gl:
