version: '3.5'
services:
  datafordeler-gl:
    build:
      context: .
      dockerfile: docker/dockerFile
    depends_on:
      - datafordeler-db
    ports:
      - 8080:80

  datafordeler-db:
    build:
      context: .
      dockerfile: docker/dockerFile.sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=testTEST1

volumes:
  datafordeler-gl:
