
--THE SEQUENCE FOR DELETING ALL CONTENT OF CVR-DATA
DELETE [Datafordeler_Test].[dbo].[cvr_industry]
DELETE [Datafordeler_Test].[dbo].[cvr_record_address]
DELETE [Datafordeler_Test].[dbo].[cvr_record_address_municipality]
DELETE [Datafordeler_Test].[dbo].[cvr_record_attribute_value]
DELETE [Datafordeler_Test].[dbo].[cvr_record_attribute]
DELETE [Datafordeler_Test].[dbo].[cvr_record_company_data_event_record]
DELETE [Datafordeler_Test].[dbo].[cvr_record_company_participant_relation_office]
DELETE [Datafordeler_Test].[dbo].[cvr_record_company_participant_relation_organization_memberdata]
DELETE [Datafordeler_Test].[dbo].[cvr_record_company_regnumber]
DELETE [Datafordeler_Test].[dbo].[cvr_record_company_status]
DELETE [Datafordeler_Test].[dbo].[cvr_record_company_unit_relation]
DELETE [Datafordeler_Test].[dbo].[cvr_record_contact]
DELETE [Datafordeler_Test].[dbo].[cvr_record_form]
DELETE [Datafordeler_Test].[dbo].[cvr_record_industry]
DELETE [Datafordeler_Test].[dbo].[cvr_record_lifecycle]
DELETE [Datafordeler_Test].[dbo].[cvr_record_metadata_contact]
DELETE [Datafordeler_Test].[dbo].[cvr_record_name1]
DELETE [Datafordeler_Test].[dbo].[cvr_record_name2]
DELETE [Datafordeler_Test].[dbo].[cvr_record_participant_metadata]
DELETE [Datafordeler_Test].[dbo].[cvr_record_unit_link_company]
DELETE [Datafordeler_Test].[dbo].[cvr_record_unit_metadata]
DELETE [Datafordeler_Test].[dbo].[cvr_status]
DELETE [Datafordeler_Test].[dbo].[cvr_form]
DELETE [Datafordeler_Test].[dbo].[cvr_municipality]
DELETE [Datafordeler_Test].[dbo].[cvr_postcode]
DELETE [Datafordeler_Test].[dbo].[cvr_record_company_metadata]
DELETE [Datafordeler_Test].[dbo].[cvr_record_company_participant_relation_office_unit]
DELETE [Datafordeler_Test].[dbo].[cvr_record_company_participant_relation_organization]
DELETE [Datafordeler_Test].[dbo].[cvr_record_fusion]
DELETE [Datafordeler_Test].[dbo].[cvr_record_monthly_numbers]
DELETE [Datafordeler_Test].[dbo].[cvr_record_quarterly_numbers]
DELETE [Datafordeler_Test].[dbo].[cvr_record_yearly_numbers]
DELETE [Datafordeler_Test].[dbo].[cvr_record_company_participant_relation]
DELETE [Datafordeler_Test].[dbo].[cvr_record_company_participant_relation_participant]
DELETE [Datafordeler_Test].[dbo].[cvr_record_status]
DELETE [Datafordeler_Test].[dbo].[cvr_record_company_participant_relation_company]

DELETE [Datafordeler_Test].[dbo].[cvr_record_company]
DELETE [Datafordeler_Test].[dbo].[cvr_record_participant]
DELETE [Datafordeler_Test].[dbo].[cvr_record_unit]

DELETE FROM [Datafordeler_Test].[dbo].[last_updated] WHERE plugin='cvr'