FROM sphinxdoc/sphinx:8.2.3 AS build_sphinx

WORKDIR /output

RUN mkdir /input
COPY docs /input

RUN sphinx-build -D language="kl" -b html /input/sphinx /output/html/kl/
RUN sphinx-build -D language="da" -b html /input/sphinx /output/html/da/
RUN sphinx-build -D language="en" -b html /input/sphinx /output/html/en/


FROM alpine:3.14 as build_swagger
WORKDIR /output
RUN mkdir /swagger
RUN wget https://github.com/swagger-api/swagger-ui/archive/refs/tags/v5.25.4.tar.gz -O - | tar xzf - -C /swagger
RUN mv /swagger/swagger-ui-5.25.4/dist /output/html
COPY docs/openapi/swagger-initializer.js /output/html
COPY docs/openapi/*.json /output/dist/openapi


FROM alpine:3.14

VOLUME /output
WORKDIR /doc
COPY ./docker/entrypoint_doc.sh /entrypoint.sh

COPY --from=build_sphinx /output/html /doc/html
COPY --from=build_swagger /output/html /doc/swagger

ENTRYPOINT ["/entrypoint.sh"]
