FROM sphinxdoc/sphinx:8.2.3 AS build_sphinx

WORKDIR /output

RUN mkdir /input
COPY docs /input

RUN sphinx-build -D language="da" -b html /input/sphinx /output/da/
#RUN sphinx-build -D language="kl" -b html /input/sphinx /output/kl/
#RUN sphinx-build -D language="en" -b html /input/sphinx /output/en/


FROM alpine:3.14 AS build_swagger
ARG COMMIT_TAG
ENV COMMIT_TAG=${COMMIT_TAG:-dev}
WORKDIR /output
RUN mkdir /swagger && \
    mkdir -p /output/openapi && \
    wget https://github.com/swagger-api/swagger-ui/archive/refs/tags/v5.25.4.tar.gz -O - | tar xzf - -C /swagger && \
    mv /swagger/swagger-ui-5.25.4/dist/* /output/
COPY docs/openapi/swagger-initializer.js /output/
COPY docs/openapi/*.json /output/openapi/
RUN find /output/openapi -type f -name '*.json' | xargs sed -i "s/{{COMMIT_TAG}}/${COMMIT_TAG}/"


FROM halverneus/static-file-server

USER static
WORKDIR /web
COPY --chown=static --from=build_sphinx /output /web
COPY --chown=static --from=build_swagger /output /web/swagger
COPY --chown=static /docs/index.html /web
