###############
# Build Stage #
###############
FROM maven:3-jdk-11 as builder
ENV MAVEN_CLI_OPTS "--batch-mode --show-version --threads 2C"

COPY pom.xml /code/pom.xml
COPY core/pom.xml /code/core/pom.xml

COPY plugin/adresseservice/pom.xml /code/plugin/adresseservice/pom.xml
COPY plugin/combinedPitu/pom.xml   /code/plugin/combinedPitu/pom.xml
COPY plugin/cpr/pom.xml   /code/plugin/cpr/pom.xml
COPY plugin/cvr/pom.xml   /code/plugin/cvr/pom.xml
COPY plugin/eboks/pom.xml   /code/plugin/eboks/pom.xml
COPY plugin/geo/pom.xml   /code/plugin/geo/pom.xml
COPY plugin/ger/pom.xml   /code/plugin/ger/pom.xml

COPY plugin/prisme/pom.xml   /code/plugin/prisme/pom.xml
COPY plugin/statistik/pom.xml   /code/plugin/statistik/pom.xml
COPY plugin/subscription/pom.xml   /code/plugin/subscription/pom.xml

WORKDIR /code/

COPY core/src /code/core/src
COPY plugin/combinedPitu/src/main /code/plugin/combinedPitu/src/main
COPY plugin/cpr/src/main /code/plugin/cpr/src/main
COPY plugin/cvr/src/main /code/plugin/cvr/src/main
COPY plugin/eboks/src/main /code/plugin/eboks/src/main
COPY plugin/geo/src/main /code/plugin/geo/src/main
COPY plugin/ger/src/main /code/plugin/ger/src/main

COPY plugin/prisme/src/main /code/plugin/prisme/src/main
COPY plugin/statistik/src/main /code/plugin/statistik/src/main
COPY plugin/subscription/src/main /code/plugin/subscription/src/main

RUN mvn $MAVEN_CLI_OPTS install -DskipTests
RUN ls -al /code/plugin/jar/*.jar
FROM openjdk:11 as dist

COPY --from=builder /code/core/target/*.jar /dist/core/
COPY --from=builder /code/plugin/jar/*.jar /dist/plugin/jar/
COPY docker/hibernate.xml /configs/hibernate.xml
COPY docker/dev-settings.properties /dist/core/application.properties

WORKDIR /dist/core
CMD ["java", "-jar", "datafordeler-core-exec.jar"]

#https://git.magenta.dk/osflow/osflow/-/blob/develop/backend/docker/Dockerfile
