###############
# Build Stage #
###############
FROM maven:3-jdk-11 as builder
ENV MAVEN_CLI_OPTS "--batch-mode --show-version --threads 2C"
COPY pom.xml /code/pom.xml

COPY core/pom.xml /code/core/pom.xml

COPY plugin/adresseservice/pom.xml /code/plugin/adresseservice/pom.xml
COPY plugin/combinedPitu/pom.xml   /code/plugin/combinedPitu/pom.xml
COPY plugin/cpr/pom.xml   /code/plugin/cpr/pom.xml
COPY plugin/cvr/pom.xml   /code/plugin/cvr/pom.xml
COPY plugin/eboks/pom.xml   /code/plugin/eboks/pom.xml
COPY plugin/geo/pom.xml   /code/plugin/geo/pom.xml
COPY plugin/ger/pom.xml   /code/plugin/ger/pom.xml

COPY plugin/prisme/pom.xml   /code/plugin/prisme/pom.xml
COPY plugin/statistik/pom.xml   /code/plugin/statistik/pom.xml
COPY plugin/subscription/pom.xml   /code/plugin/subscription/pom.xml

WORKDIR /code/
#RUN mvn $MAVEN_CLI_OPTS de.qaware.maven:go-offline-maven-plugin:resolve-dependencies
COPY core/src /code/core/src
COPY plugin/combinedPitu/src/main /code/plugin/combinedPitu/src/main
COPY plugin/cpr/src/main /code/plugin/cpr/src/main
COPY plugin/cvr/src/main /code/plugin/cvr/src/main
COPY plugin/eboks/src/main /code/plugin/eboks/src/main
COPY plugin/geo/src/main /code/plugin/geo/src/main
COPY plugin/ger/src/main /code/plugin/ger/src/main

COPY plugin/prisme/src/main /code/plugin/prisme/src/main
COPY plugin/statistik/src/main /code/plugin/statistik/src/main
COPY plugin/subscription/src/main /code/plugin/subscription/src/main

RUN mvn $MAVEN_CLI_OPTS package -DskipTests
RUN ls -al /code/plugin/jar/*.jar
FROM openjdk:11 as dist

COPY --from=builder /code/core/target/*.jar /dist/core/
COPY --from=builder /code/plugin/jar/*.jar /dist/plugin/jar/
COPY docker/hibernate.xml /configs/hibernate.xml
COPY docker/dev-settings.properties /dist/core/application.properties

WORKDIR /dist/core
#CMD ["tail", "-f", "/dev/null"]
CMD ["java", "-jar", "datafordeler-core-exec.jar"]

#FROM maven:3-jdk-11
#run mkdir /app
#COPY core /app/core
#COPY ci /app/ci
#WORKDIR /app/core
#RUN mvn --batch-mode -T 2C package install -DskipTests
#COPY plugin /app/plugin
#ADD ci/build_plugins.sh /app/plugin/build_plugins.sh
#WORKDIR /app/plugin
#RUN chmod +x /app/plugin/build_plugins.sh
#RUN /app/plugin/build_plugins.sh

#WORKDIR /app/plugin/cpr
#RUN mvn --batch-mode -T 2C package install -DskipTests

#WORKDIR /app/plugin/geo
#RUN mvn --batch-mode -T 2C package install -DskipTests

#WORKDIR /app/plugin/cvr
#RUN mvn --batch-mode -T 2C package install -DskipTests

#WORKDIR /app/plugin/ger
#RUN mvn --batch-mode -T 2C package install -DskipTests

#WORKDIR /app/plugin/eboks
#RUN mvn --batch-mode -T 2C package install -DskipTests

#WORKDIR /app/plugin/prisme
#RUN mvn --batch-mode -T 2C package install -DskipTests

#WORKDIR /app/plugin/subscription
#RUN mvn --batch-mode -T 2C package install -DskipTests

#WORKDIR /app/plugin/combinedPitu
#RUN mvn --batch-mode -T 2C package install -DskipTests

#TODO WE NEED TO FIX TESTS OF STATISTICS
#WORKDIR /app/plugin/statistik
#RUN mvn --batch-mode -T 2C package install -DskipTests
#ENTRYPOINT [""]
#CMD [""]
#java -jar datafordeler-core-exec.jar --spring.config.location="classpath:/application.properties,file:%DIR%local_settings.properties"
#https://git.magenta.dk/osflow/osflow/-/blob/develop/backend/docker/Dockerfile
