FROM jelastic/maven:3.9.9-openjdk-23.0.1-almalinux-9 AS build

WORKDIR /build/

COPY pom.xml pom.xml
COPY parent/pom.xml parent/pom.xml
COPY core/pom.xml core/pom.xml
COPY plugin/geo/pom.xml plugin/geo/pom.xml
COPY plugin/combinedPitu/pom.xml plugin/combinedPitu/pom.xml
COPY plugin/cpr/pom.xml plugin/cpr/pom.xml
COPY plugin/cvr/pom.xml plugin/cvr/pom.xml
COPY plugin/eboks/pom.xml plugin/eboks/pom.xml
COPY plugin/eskat/pom.xml plugin/eskat/pom.xml
COPY plugin/ger/pom.xml plugin/ger/pom.xml
COPY plugin/prisme/pom.xml plugin/prisme/pom.xml
COPY plugin/statistik/pom.xml plugin/statistik/pom.xml
COPY plugin/subscription/pom.xml plugin/subscription/pom.xml

RUN mvn verify --fail-never

COPY core core
COPY plugin plugin

RUN mvn install -DskipTests --batch-mode --show-version


FROM eclipse-temurin:23-jre-alpine

ARG COMMIT_TAG
ENV COMMIT_TAG=${COMMIT_TAG:-HEAD}

RUN apk add --no-cache jattach --repository http://dl-cdn.alpinelinux.org/alpine/edge/community/

COPY docker/entrypoint.sh /app/entrypoint.sh
COPY --from=build /build/core/target/*.jar /app/core/
COPY --from=build /build/plugin/jar/*.jar /app/plugin/





EXPOSE 8000
ENTRYPOINT ["/app/entrypoint.sh"]
CMD [ \
    "java", \
    "-Dloader.path=/app/plugin/", \
    "-Xms4g", "-Xmx8g", \
    "-XX:+HeapDumpOnOutOfMemoryError", "-XX:HeapDumpPath=/app/log", \
    "-XX:+UseShenandoahGC", "-XX:+UnlockExperimentalVMOptions", "-XX:ShenandoahUncommitDelay=1000", "-XX:ShenandoahGuaranteedGCInterval=10000", \
    "-Djava.rmi.server.hostname=127.0.0.1", "-Dcom.sun.management.jmxremote.rmi.port=7012", "-Dcom.sun.management.jmxremote.port=7012", "-Dcom.sun.management.jmxremote.authenticate=false", "-Dcom.sun.management.jmxremote.ssl=false", \
    "-cp", "/app/core/datafordeler-core-exec.jar", "org.springframework.boot.loader.launch.PropertiesLauncher" \
]
