FROM jelastic/maven:3.9.9-openjdk-23.0.1-almalinux-9 AS dependencies

WORKDIR /build/

# Fetch dependencies and put them in a docker layer, so we can rebuild without donwloading all dependencies again
RUN --mount=type=cache,target=/root/.m2 \
    --mount=type=bind,source=pom.xml,target=pom.xml \
    --mount=type=bind,source=parent/pom.xml,target=parent/pom.xml \
    --mount=type=bind,source=core/pom.xml,target=core/pom.xml \
    --mount=type=bind,source=plugin/adresseservice/pom.xml,target=plugin/adresseservice/pom.xml \
    --mount=type=bind,source=plugin/combinedPitu/pom.xml,target=plugin/combinedPitu/pom.xml \
    --mount=type=bind,source=plugin/cpr/pom.xml,target=plugin/cpr/pom.xml \
    --mount=type=bind,source=plugin/cvr/pom.xml,target=plugin/cvr/pom.xml \
    --mount=type=bind,source=plugin/eboks/pom.xml,target=plugin/eboks/pom.xml \
    --mount=type=bind,source=plugin/eskat/pom.xml,target=plugin/eskat/pom.xml \
    --mount=type=bind,source=plugin/geo/pom.xml,target=plugin/geo/pom.xml \
    --mount=type=bind,source=plugin/ger/pom.xml,target=plugin/ger/pom.xml \
    --mount=type=bind,source=plugin/prisme/pom.xml,target=plugin/prisme/pom.xml \
    --mount=type=bind,source=plugin/statistik/pom.xml,target=plugin/statistik/pom.xml \
    --mount=type=bind,source=plugin/subscription/pom.xml,target=plugin/subscription/pom.xml \
    mvn dependency:go-offline -DskipTests --batch-mode --show-version --threads 2C


FROM dependencies AS package

WORKDIR /build

# Compile
RUN --mount=type=cache,target=/root/.m2 \
    --mount=type=bind,source=pom.xml,target=pom.xml \
    --mount=type=bind,source=parent/pom.xml,target=parent/pom.xml \
    --mount=type=bind,source=core/pom.xml,target=core/pom.xml \
    --mount=type=bind,source=core/src,target=/build/core/src \
    --mount=type=bind,source=plugin/adresseservice/src,target=plugin/adresseservice/pom.xml \
    --mount=type=bind,source=plugin/adresseservice/pom.xml,target=plugin/adresseservice/pom.xml \
    --mount=type=bind,source=plugin/combinedPitu/pom.xml,target=plugin/combinedPitu/pom.xml \
    --mount=type=bind,source=plugin/combinedPitu/src,target=plugin/combinedPitu/src \
    --mount=type=bind,source=plugin/cpr/pom.xml,target=plugin/cpr/pom.xml \
    --mount=type=bind,source=plugin/cpr/src,target=plugin/cpr/src \
    --mount=type=bind,source=plugin/cvr/pom.xml,target=plugin/cvr/pom.xml \
    --mount=type=bind,source=plugin/cvr/src,target=plugin/cvr/src \
    --mount=type=bind,source=plugin/eboks/pom.xml,target=plugin/eboks/pom.xml \
    --mount=type=bind,source=plugin/eboks/src,target=plugin/eboks/src \
    --mount=type=bind,source=plugin/eskat/pom.xml,target=plugin/eskat/pom.xml \
    --mount=type=bind,source=plugin/eskat/src,target=plugin/eskat/src \
    --mount=type=bind,source=plugin/geo/pom.xml,target=plugin/geo/pom.xml \
    --mount=type=bind,source=plugin/geo/src,target=plugin/geo/src \
    --mount=type=bind,source=plugin/ger/pom.xml,target=plugin/ger/pom.xml \
    --mount=type=bind,source=plugin/ger/src,target=plugin/ger/src \
    --mount=type=bind,source=plugin/prisme/pom.xml,target=plugin/prisme/pom.xml \
    --mount=type=bind,source=plugin/prisme/src,target=plugin/prisme/src \
    --mount=type=bind,source=plugin/statistik/pom.xml,target=plugin/statistik/pom.xml \
    --mount=type=bind,source=plugin/statistik/src,target=plugin/statistik/src \
    --mount=type=bind,source=plugin/subscription/pom.xml,target=plugin/subscription/pom.xml \
    mvn package -DskipTests --batch-mode --show-version --threads 2C


FROM eclipse-temurin:23-jre-alpine AS final
WORKDIR /app
ARG COMMIT_TAG
ENV COMMIT_TAG=${COMMIT_TAG:-HEAD}
RUN apk add --no-cache bash

# Copy compiled jars to slim executable container with just a JRE
COPY --from=package /build/core/target/*.jar /app/core/
COPY --from=package /build/plugin/jar/*.jar /app/plugin/
COPY --chmod=0500 docker/entrypoint.sh /app/entrypoint.sh

# For testing
COPY conf/sts_metadata.test.xml /app/conf/sts_metadata.test.xml
COPY plugin/cpr/data/keyfile.json /tmp/test_cpr_key.json

EXPOSE 8000
ENTRYPOINT ["/app/entrypoint.sh"]
CMD ["java", "-Dloader.path=/app/plugin/", "-cp", "/app/core/datafordeler-core-exec.jar", "org.springframework.boot.loader.launch.PropertiesLauncher"]
