FROM jelastic/maven:3.9.9-openjdk-23.0.1-almalinux-9 AS build

WORKDIR /build/

COPY pom.xml pom.xml
COPY parent/pom.xml parent/pom.xml
COPY core core
COPY plugin plugin

RUN mvn install -DskipTests --batch-mode --show-version --threads 2C


FROM eclipse-temurin:23-jre-alpine

ARG COMMIT_TAG
ENV COMMIT_TAG=${COMMIT_TAG:-HEAD}
RUN apk add --no-cache jattach --repository http://dl-cdn.alpinelinux.org/alpine/edge/community/

COPY docker/entrypoint.sh /app/entrypoint.sh
COPY --from=build /build/core/target/*.jar /app/core/
COPY --from=build /build/plugin/jar/*.jar /app/plugin/

EXPOSE 8000
ENTRYPOINT ["/app/entrypoint.sh"]
CMD ["java", "-Xms4g", "-Xmx8g", "-XX:+HeapDumpOnOutOfMemoryError", "-XX:HeapDumpPath=/app/log", "-Dloader.path=/app/plugin/", "-XX:+UseShenandoahGC", "-XX:+UnlockExperimentalVMOptions", "-XX:ShenandoahUncommitDelay=1000", "-XX:ShenandoahGuaranteedGCInterval=10000", "-cp", "/app/core/datafordeler-core-exec.jar", "org.springframework.boot.loader.launch.PropertiesLauncher"]
