FROM swaggerapi/swagger-ui
COPY docs/openapi/*.json /usr/share/nginx/html/dafo/
ENV URLS='[{ name: "generic", url: "/dafo/openapi.json"},{ name: "combined", url: "/dafo/combinedapi.json" },{ name: "custody", url: "/dafo/cprapi.json" },{ name: "prisme", url: "/dafo/prismeapi.json" },{ name: "subscription", url: "/dafo/subscriptionapi.json" }]'
