
TRUNCATE TABLE [Datafordeler_Test].[dbo].[cpr_person_address_coname_record];
TRUNCATE TABLE [Datafordeler_Test].[dbo].[cpr_person_address_name_record];
TRUNCATE TABLE [Datafordeler_Test].[dbo].[cpr_person_address_record];
TRUNCATE TABLE [Datafordeler_Test].[dbo].[cpr_person_birthplace_record];
TRUNCATE TABLE [Datafordeler_Test].[dbo].[cpr_person_birthplace_verification_record];
TRUNCATE TABLE [Datafordeler_Test].[dbo].[cpr_person_birthtime_record];
TRUNCATE TABLE [Datafordeler_Test].[dbo].[cpr_person_children_record];
TRUNCATE TABLE [Datafordeler_Test].[dbo].[cpr_person_church_record];
TRUNCATE TABLE [Datafordeler_Test].[dbo].[cpr_person_church_verification_record];
TRUNCATE TABLE [Datafordeler_Test].[dbo].[cpr_person_citizenship_record];
TRUNCATE TABLE [Datafordeler_Test].[dbo].[cpr_person_citizenship_verification_record];
TRUNCATE TABLE [Datafordeler_Test].[dbo].[cpr_person_civilstatus_authoritytext_record];
TRUNCATE TABLE [Datafordeler_Test].[dbo].[cpr_person_civilstatus_record];
TRUNCATE TABLE [Datafordeler_Test].[dbo].[cpr_person_civilstatus_verification_record];
TRUNCATE TABLE [Datafordeler_Test].[dbo].[cpr_person_core_record];
TRUNCATE TABLE [Datafordeler_Test].[dbo].[cpr_person_custody_record];
TRUNCATE TABLE [Datafordeler_Test].[dbo].[cpr_person_event_record];
TRUNCATE TABLE [Datafordeler_Test].[dbo].[cpr_person_foreignaddress_migration_record];
TRUNCATE TABLE [Datafordeler_Test].[dbo].[cpr_person_foreignaddress_record];
TRUNCATE TABLE [Datafordeler_Test].[dbo].[cpr_person_guardian_record];
TRUNCATE TABLE [Datafordeler_Test].[dbo].[cpr_person_movemunicipality_record];
TRUNCATE TABLE [Datafordeler_Test].[dbo].[cpr_person_name_authoritytext_record];
TRUNCATE TABLE [Datafordeler_Test].[dbo].[cpr_person_name_record];
TRUNCATE TABLE [Datafordeler_Test].[dbo].[cpr_person_name_verification_record];
TRUNCATE TABLE [Datafordeler_Test].[dbo].[cpr_person_number_record];
TRUNCATE TABLE [Datafordeler_Test].[dbo].[cpr_person_parent_record];
TRUNCATE TABLE [Datafordeler_Test].[dbo].[cpr_person_parent_verification_record];
TRUNCATE TABLE [Datafordeler_Test].[dbo].[cpr_person_position_record];
TRUNCATE TABLE [Datafordeler_Test].[dbo].[cpr_person_protection_record];
TRUNCATE TABLE [Datafordeler_Test].[dbo].[cpr_person_status_record];
TRUNCATE TABLE [Datafordeler_Test].[dbo].[cpr_person_subscription_list];
DELETE [dafotestdb007].[dbo].[cpr_person_entity];

