# Playbook for server
---

- hosts: default

  remote_user: vagrant
  become: true
  become_method: sudo
  become_user: root

  roles:
  - vim
  - python
  - pip_dependencies
  - activate_virtualenv

...
