FROM maven:3-jdk-11



run mkdir /app
COPY core /app/core
WORKDIR /app/core
RUN mvn --batch-mode -T 2C package install -DskipTests
COPY plugin /app/plugin
#ADD ci/build_plugins.sh /app/plugin/build_plugins.sh
#WORKDIR /app/plugin
#RUN chmod +x /app/plugin/build_plugins.sh
#RUN /app/plugin/build_plugins.sh

WORKDIR /app/plugin/cpr
RUN mvn --batch-mode -T 2C package install -DskipTests

WORKDIR /app/plugin/geo
RUN mvn --batch-mode -T 2C package install -DskipTests

WORKDIR /app/plugin/cvr
RUN mvn --batch-mode -T 2C package install -DskipTests

WORKDIR /app/plugin/ger
RUN mvn --batch-mode -T 2C package install -DskipTests

WORKDIR /app/plugin/eboks
RUN mvn --batch-mode -T 2C package install -DskipTests

WORKDIR /app/plugin/prisme
RUN mvn --batch-mode -T 2C package install -DskipTests

#TODO WE NEED TO FIX TESTS OF STATISTICS
WORKDIR /app/plugin/statistik
RUN mvn --batch-mode -T 2C package install -DskipTests

RUN unlink /etc/localtime
RUN ln -s /usr/share/zoneinfo/Europe/Copenhagen /etc/localtime
#ENTRYPOINT ["entrypoint.sh"]

WORKDIR /app/core
RUN mvn test

WORKDIR /app/plugin/cpr
RUN mvn test

WORKDIR /app/plugin/geo
RUN mvn test

WORKDIR /app/plugin/cvr
RUN mvn test

WORKDIR /app/plugin/ger
RUN mvn test

WORKDIR /app/plugin/eboks
RUN mvn test

WORKDIR /app/plugin/prisme
RUN mvn test

WORKDIR /app/plugin/statistik
RUN mvn test


