FROM maven:3-jdk-11



run mkdir /app
COPY core /app/core
COPY ci /app/ci
WORKDIR /app/core
RUN mvn --batch-mode -T 2C package install -DskipTests -Dorg.slf4j.simpleLogger.defaultLogLevel=WARN
COPY plugin /app/plugin
#ADD ci/build_plugins.sh /app/plugin/build_plugins.sh
#WORKDIR /app/plugin
#RUN chmod +x /app/plugin/build_plugins.sh
#RUN /app/plugin/build_plugins.sh

WORKDIR /app/plugin/cpr
RUN mvn --batch-mode -T 2C package install -DskipTests -Dorg.slf4j.simpleLogger.defaultLogLevel=WARN

WORKDIR /app/plugin/geo
RUN mvn --batch-mode -T 2C package install -DskipTests -Dorg.slf4j.simpleLogger.defaultLogLevel=WARN

WORKDIR /app/plugin/cvr
RUN mvn --batch-mode -T 2C package install -DskipTests -Dorg.slf4j.simpleLogger.defaultLogLevel=WARN

WORKDIR /app/plugin/ger
RUN mvn --batch-mode -T 2C package install -DskipTests -Dorg.slf4j.simpleLogger.defaultLogLevel=WARN

WORKDIR /app/plugin/eboks
RUN mvn --batch-mode -T 2C package install -DskipTests -Dorg.slf4j.simpleLogger.defaultLogLevel=WARN

WORKDIR /app/plugin/prisme
RUN mvn --batch-mode -T 2C package install -DskipTests -Dorg.slf4j.simpleLogger.defaultLogLevel=WARN

#TODO WE NEED TO FIX TESTS OF STATISTICS
WORKDIR /app/plugin/statistik
RUN mvn --batch-mode -T 2C package install -DskipTests -Duser.timezone=Europe/Copenhagen

WORKDIR /app/ci
ENTRYPOINT ["./entrypoint.sh"]




