@echo off
rem
rem In this file local configuration parameters can be added.
rem


set DATABASE_URL=%DATABASE_URL%
set DATABASE_USERNAME=%DATABASE_USERNAME%
set DATABASE_PASSWORD=%DATABASE_PASSWORD%

set USERSTORE_URL=%USERSTORE_URL%
set USERSTORE_USERNAME=%USERSTORE_USERNAME%
set USERSTORE_PASSWORD=%USERSTORE_PASSWORD%
